### ISSUE TITLE
Maintenance of this project

### ISSUE THREAD

**Issue by mormahr** [alex-whitney/express-promise-router#33]
I can't say how much i appreciate this module and how much i use it. But it seems like you don't really come around to maintain it anymore which makes continuos improvements and updates harder (due to long response times). I would very much appreciate it if you would add someone as a project member to help you out with maintenance. As you might have noticed i put some effort into updating "legacy" parts of this module to make it fit for the future.

And thanks for your work again! ☺️

**Comment by mormahr** [comment]
@alex-whitney just wanted to bump this in case you have some spare time ☺️

**Comment by friday** [comment]
Seems like he is MIA since september 19, 2016. The lack of response suggests he's not reachable this way, or are you @alex-whitney?
Maybe he can be reached through his email (`npm owner ls express-promise-router`).

NPM would most likely give you the package name if you want to maintain the project @mormahr (looks like you already are unofficially). You case is described here: https://docs.npmjs.com/misc/disputes

**Comment by mormahr** [comment]
@friday Thanks for the reminder! ☺️

**Comment by alex-whitney** [comment]
Sorry for being MIA! This was a little project I built on a whim and never even ended up using, so needless to say I was surprised when people found and started using it. Thanks for taking interest in this project and wanting to continue to improve and maintain it. I've already added you @mormahr as a maintainer, I'll connect with you separately to give you access on NPM.
